apiVersion: v1
kind: Service
metadata:
  name: flink-native-nodeport-rest
spec:
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
      nodePort: 32007
  selector:
    app: flink-native
    component: jobmanager